MontalcinoForecastsApp/urls.py
from django.urls import path

from MontalcinoForecastsApp import views

app_name = 'MontalcinoForecastsApp'
urlpatterns = [
    path('', views.simplified, name='simplified'),
    path('complete', views.complete, name='complete'),
    path('help', views.help_page, name='help'),
    path('ajax/getBestRegressors', views.ajax_get_best_regressors, name='ajax_get_best_regressors'),
    path('ajax/getForecast', views.ajax_get_forecast, name='ajax_get_forecast'),
    path('ajax/getBestRegressors/<str:stD>&<str:stE>', views.ajax_get_best_regressors, name='ajax_get_best_regressors'),
    path('ajax/getForecast', views.ajax_get_forecast, name='ajax_get_forecast')
]

VineyardsDataAnalysis/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('MontalcinoForecastsApp/', include('MontalcinoForecastsApp.urls')),
    path('WinePredictionREST/', include('WinePredictionREST.urls')),

]

"""    path('WineApp/', include('WineApp.urls')),
    path('MontalcinoForecastsApp/', include('MontalcinoForecastsApp.urls')),
    path('WinePredictionREST/', include('WinePredictionREST.urls')),"""

WineApp/urls.py
from django.urls import path

from WineApp import views

app_name = 'WineApp'
urlpatterns = [
    # Index Dashboard
    path('', views.show_index, name='show.index'),
    path('ajax/getIndex', views.ajax_get_index, name='ajax.getIndex'),
    path('ajax/updateIndex', views.ajax_update_index, name='ajax.updateIndex'),

    # Daily Dashboard
    path('dailyData', views.show_daily_data, name='show.dailyData'),
    path('ajax/getDailyData', views.ajax_get_daily_data, name='ajax.getDailyData'),
    path('ajax/updateDailyData', views.ajax_update_daily_data, name='ajax.updateDailyData'),

    # Hourly Dashboard
    path('hourlyData', views.show_hourly_data, name='show.hourlyData'),
    path('ajax/getHourlyData', views.ajax_get_hourly_data, name='ajax.getHourlyData'),
    path('ajax/updateHourlyData', views.ajax_update_hourly_data, name='ajax.updateHourlyData'),

    # Anomalies Dashboard
    path('anomalies', views.show_anomalies, name='show.anomalies'),
    path('ajax/getAnomalies', views.ajax_get_anomalies, name='ajax.getAnomalies'),
    path('ajax/updateAnomalies', views.ajax_update_anomalies, name='ajax.updateAnomalies')
]

MontalcinoForecastsApp/models.py
import numpy as np

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import IntegrityError
from polymorphic.models import PolymorphicModel

from WineApp.models import Sensor, DailyData

# Create your models here.


class Wine(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Vintage(models.Model):
    year = models.IntegerField()
    value = models.FloatField(
        validators=[
            MaxValueValidator(5.0),
            MinValueValidator(1.0)
        ]
    )
    wine = models.ForeignKey(Wine, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('year', 'wine')

    def __str__(self):
        return str(self.year) + " - " + self.wine.name


class ClimaticIndex(PolymorphicModel):
    name = models.CharField(max_length=200, default="")
    sensor = models.ForeignKey(Sensor, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_list(self, start_date, end_date):
        raise IntegrityError("Objects of type 'ClimaticIndex' shouldn't exist, only subclasses can exist.")


class MonthsAvgIndex(ClimaticIndex):
    start_month = models.IntegerField(
        validators=[
            MaxValueValidator(12),
            MinValueValidator(1)
        ]
    )
    end_month = models.IntegerField(
        validators=[
            MaxValueValidator(12),
            MinValueValidator(1)
        ]
    )

    class Meta:
        verbose_name_plural = 'Months Avg indices'

    def get_list(self, start_date, end_date):
        values_list = []
        start_year = start_date.year
        end_year = end_date.year
        query_set = DailyData.objects.filter(sensor=self.sensor, date__gte=start_date, date__lte=end_date)\
            .exclude(avg=None).filter(date__month__gte=self.start_month, date__month__lte=self.end_month)
        if query_set:
            for year in range(start_year, end_year + 1):
                year_set = query_set.filter(date__year=year)
                if year_set:
                    values_list.append(year_set.aggregate(models.Avg('avg')).get('avg__avg'))
                else:
                    values_list.append(np.nan)
            return values_list
        else:
            return None


class WinklerIndex(ClimaticIndex):

    def save(self, *args, **kwargs):
        queryset = WinklerIndex.objects.all()
        if not queryset:
            self.sensor = Sensor.objects.get(name="Temperatura aria")
            super(ClimaticIndex, self).save(*args, **kwargs)

    def get_list(self, start_date, end_date):
        values_list = []
        start_year = start_date.year
        end_year = end_date.year
        query_set = DailyData.objects.filter(sensor=self.sensor, date__gte=start_date, date__lte=end_date)\
            .exclude(avg=None).filter(date__month__gte=4, date__month__lte=10)
        if query_set:
            for year in range(start_year, end_year + 1):
                year_set = query_set.filter(date__year=year)
                if year_set:
                    wi_index = 0
                    for dayli_data in year_set:
                        if dayli_data.avg > 10:
                            wi_index += dayli_data.avg - 10
                    values_list.append(wi_index)
                else:
                    values_list.append(np.nan)
            return values_list
        else:
            return None


class HuglinIndex(ClimaticIndex):

    def save(self, *args, **kwargs):
        queryset = HuglinIndex.objects.all()
        if not queryset:
            self.sensor = Sensor.objects.get(name="Temperatura aria")
            super(ClimaticIndex, self).save(*args, **kwargs)

    def get_list(self, start_date, end_date):
        values_list = []
        start_year = start_date.year
        end_year = end_date.year
        query_set = DailyData.objects.filter(sensor=self.sensor, date__gte=start_date, date__lte=end_date). \
            exclude(avg=None, max=None).filter(date__month__gte=4, date__month__lte=9)
        if query_set:
            k = 1.03
            for year in range(start_year, end_year + 1):
                year_set = query_set.filter(date__year=year)
                if year_set:
                    hi_index = 0
                    for dayli_data in year_set:
                        hi_index += (dayli_data.avg + dayli_data.max - 20) / 2 * k
                    values_list.append(hi_index)
                else:
                    values_list.append(np.nan)
            return values_list
        else:
            return None

MontalcinoForecastsApp/views.py
from datetime import datetime
import statsmodels.api as sm
from more_itertools.recipes import powerset

from django.http import JsonResponse
from django.shortcuts import render
from django.db.models import Min, Max
from MontalcinoForecastsApp.utils import *

from django.views.decorators.csrf import csrf_exempt

# Create your views here.


def help_page(request):
    return render(request, "MontalcinoForecastsApp/help.html")


def complete(request):
    earliest_db_str = DailyData.objects.all().aggregate(Min("date")).get('date__min').strftime('%d/%m/%Y')
    latest_db_str = DailyData.objects.all().aggregate(Max("date")).get('date__max').strftime('%d/%m/%Y')
    context = {'start_db': earliest_db_str, 'end_db': latest_db_str}

    form_regressors = ClimaticIndex.objects.all().values('id', 'name')
    context['form_regressors'] = form_regressors

    if request.method == "POST" and request.POST.get('startDate') is not None:

        start_date_str = request.POST.get('startDate')
        end_date_str = request.POST.get('endDate')
        start_date = datetime.strptime(start_date_str, "%d/%m/%Y").date()
        end_date = datetime.strptime(end_date_str, "%d/%m/%Y").date()

        # Creation of lists of vintages
        vintages = get_vintages_list(start_date, end_date)
        if vintages is None:
            context['err_msg'] = "Dati sulle annate mancanti tra il " + start_date_str + " e il " + end_date_str
            return render(request, "MontalcinoForecastsApp/complete.html", context)

        # Data array creation
        regr_combo = get_regr_combo(request.POST)
        x, regr_list, failed_regr_list = get_data(start_date, end_date, regr_combo)

        # Error if unable to get all data (all nan or all nan except one)
        if len(failed_regr_list) > 0:
            err_msg = "Dati mancanti o non sufficienti tra il " + start_date_str + " e il " + end_date_str + \
                                 " per poter calcolare i seguenti indici: "
            for regr in failed_regr_list:
                err_msg += regr + ", "
            context['err_msg'] = err_msg[:-2] + "."
            return render(request, "MontalcinoForecastsApp/complete.html", context)

        # Error if no regressor was selected
        if len(regr_list) is 0:
            context['err_msg'] = "Nessun indice selezionato"
            return render(request, "MontalcinoForecastsApp/complete.html", context)

        # Error if more regressors than data
        if len(vintages) <= len(regr_list):
            err_msg = "Pochi anni e troppi regressori, impossibile usare la regressione lineare."
            context['err_msg'] = err_msg
            return render(request, "MontalcinoForecastsApp/complete.html", context)

        # Linear regression
        x2 = sm.add_constant(x, has_constant='add')
        model = sm.OLS(vintages, x2)
        results = model.fit()
        vin_pred = results.predict(x2)

        # Chart and cards data creation
        chart = create_quality_chart(vintages, vin_pred)
        icons = get_icons(regr_combo)
        table_data = list(zip(["Intercetta"] + regr_list, ["fas fa-chart-line"] + icons,
                              results.params, results.pvalues))

        # Update context
        context['start_train_date'] = start_date_str
        context['end_train_date'] = end_date_str
        context['chart_out'] = chart.render()
        context['regr_count'] = len(regr_list)
        context['r2'] = results.rsquared
        context['adj_r2'] = results.rsquared_adj
        context['table_data'] = table_data
        context['anchor'] = "results-section"
        context['regr_combo'] = regr_combo

        return render(request, "MontalcinoForecastsApp/complete.html", context)

    else:
        return render(request, "MontalcinoForecastsApp/complete.html", context)


def simplified(request):
    earliest_db_str = DailyData.objects.all().aggregate(Min("date")).get('date__min').strftime('%d/%m/%Y')
    latest_db_str = DailyData.objects.all().aggregate(Max("date")).get('date__max').strftime('%d/%m/%Y')
    context = {'start_db': earliest_db_str, 'end_db': latest_db_str}
    return render(request, "MontalcinoForecastsApp/simplified.html", context)

@csrf_exempt
def ajax_get_best_regressors(request,stD='',stE=''):
    start_date_str = request.POST.get('startDate',stD)
    end_date_str = request.POST.get('endDate',stE)
    if stD != '':
        start_date = datetime.strptime(start_date_str, "%d-%m-%Y").date()
    else: 
        start_date = datetime.strptime(start_date_str, "%d/%m/%Y").date()
    if stE != '':
        end_date = datetime.strptime(end_date_str, "%d-%m-%Y").date()
    else:
        end_date = datetime.strptime(end_date_str, "%d/%m/%Y").date()  
    """
        start_date = datetime.strptime(start_date_str, "%d/%m/%Y").date()
        end_date = datetime.strptime(end_date_str, "%d/%m/%Y").date()
    """
    # Creation of lists of vintages and years
    vintages = get_vintages_list(start_date, end_date)
    if vintages is None:
        err_msg = "Dati sulle annate mancanti tra il " + start_date_str + " e il " + end_date_str
        return JsonResponse({"err_msg": err_msg})

    # Get data for all the regressors
    regressors_set = ClimaticIndex.objects.all()
    dict_ids_values_regr = {}
    ids_list = []
    failed_regr_names = []
    for regr in regressors_set:
        values_list = regr.get_list(start_date, end_date)
        if values_list is not None and not (values_list.count(np.nan) is len(values_list) - 1 and
                                            len(values_list) is not 1):
            # Imputation of missing values
            values_list = np.array(values_list).reshape((-1, 1))
            imp = SimpleImputer(missing_values=np.nan, strategy='mean')
            values_list = imp.fit_transform(values_list)

            dict_ids_values_regr[regr.id] = {'values_list': values_list, 'regr': regr}
            ids_list.append(regr.id)
        else:
            failed_regr_names.append(regr.name)

    # Error if no data
    if len(dict_ids_values_regr) is 0:
        err_msg = "Dati meteorologici mancanti tra il " + start_date_str + " e il " + end_date_str
        return JsonResponse({"err_msg": err_msg})

    # Generate all combinations and run all the possible linear regressions
    combo_list = list(powerset(ids_list))
    combo_list.pop(0)
    n_years = len(vintages)
    models_results = []
    for combo in combo_list:
        # Check if observations > regressors
        if n_years > len(combo):
            x = np.ones(end_date.year - start_date.year + 1)
            current_regressors = []
            for id in combo:
                x = np.column_stack((x, dict_ids_values_regr[id]['values_list']))
                current_regressors.append(dict_ids_values_regr[id]['regr'])
            # No need to add the constant
            result = sm.OLS(vintages, x).fit()
            models_results.append({'result': result, 'regr_list': current_regressors})

    # Filter models with all p-values < threshold and sort by adj R^2
    pvalues_threshold = 0.2
    best_pvalues_models = list(filter(lambda mod: all(k <= pvalues_threshold for k in mod["result"].pvalues),
                                      models_results))
    best_pvalues_models.sort(key=lambda mod: mod["result"].rsquared_adj, reverse=True)

    # Alternative: filter models with all p-values < increasing threshold, stop at the smallest and sort by adj R^2
    '''
    best_pvalues_models = []
    pvalues_thresholds = [0.01, 0.05, 0.1, 0.2, 0.3]
    for pvalues_threshold in pvalues_thresholds:
        best_pvalues_models = list(filter(lambda mod: all(k <= pvalues_threshold for k in mod["result"].pvalues),
                                          models_results))
        if len(best_pvalues_models) is not 0:
            best_pvalues_models.sort(key=lambda mod: mod["result"].rsquared_adj, reverse=True)
            break
    '''

    # Error if no match found
    if len(best_pvalues_models) is 0:
        err_msg = "Impossibile determinare il miglior modello tra il " + start_date_str + " e il " + end_date_str + \
                  ". Selezionare un altro range di date."
        return JsonResponse({"err_msg": err_msg})

    # Return the results for the best 4 combinations
    best_results_summary = []
    for mod in best_pvalues_models[:4]:
        content = {}
        content['regr_list'] = [regr.name for regr in mod['regr_list']]
        content['icons'] = [regr.sensor.icon for regr in mod['regr_list']]
        content['regr_combo'] = [regr.id for regr in mod['regr_list']]
        content['adj_r2'] = mod["result"].rsquared_adj
        content['p_values'] = mod["result"].pvalues.tolist()
        best_results_summary.append(content)
    return JsonResponse({"results": best_results_summary, "failed_regressors": failed_regr_names,
                         "pvalues_threshold": pvalues_threshold})

@csrf_exempt
def ajax_get_forecast(request,startDate='',endDate='',regrcombo = []):
    start_date_str = request.POST.get('startTrainDate',startDate)
    end_date_str = request.POST.get('endTrainDate',endDate)
    start_date = datetime.strptime(start_date_str, "%d/%m/%Y").date()
    end_date = datetime.strptime(end_date_str, "%d/%m/%Y").date()

    forecast_year = int(request.POST.get('forecastYear'))
    start_forecast_date = datetime(forecast_year, 1, 1).date()
    end_forecast_date = datetime(forecast_year, 12, 31).date()

    regr_combo = request.POST.getlist('regrCombo[]',regrcombo)

    # Train regression
    vintages = get_vintages_list(start_date, end_date)
    x, regr_list, failed_regr_list = get_data(start_date, end_date, regr_combo)
    x2 = sm.add_constant(x, has_constant='add')
    model = sm.OLS(vintages, x2)
    results = model.fit()

    # Make the prediction
    x, regr_list, failed_regr_list = get_data(start_forecast_date, end_forecast_date, regr_combo)
    if len(failed_regr_list) > 0:

MontalcinoForecastsApp/templates/MontalcinoForecastsApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Montalcino Forecasts App</title>

    {% load static %}
    <link rel="icon" href="{% static "MontalcinoForecastsApp/img/icon.png" %}" type="image/png"/>
    
    <!-- Stylesheets -->
    
    <!-- Bootstrap, fonts, icons -->
    <link rel="stylesheet" type="text/css" href="{% static "lib/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "fonts/poppins/poppins.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "fonts/fontawesome/css/all.min.css" %}">
    
    <!-- Air-datepicker -->
    <link rel="stylesheet" type="text/css" href="{% static 'MontalcinoForecastsApp/lib/air-datepicker/css/datepicker.min.css' %}">
    
    <style>
        #top-btn {
            background: url({% static 'MontalcinoForecastsApp/img/cd-top-arrow.svg' %}) no-repeat center 50%;
        }
        .spinner {
            background-image: url({% static 'MontalcinoForecastsApp/img/spinner.svg' %});
        }
    </style>
    
    <link rel="stylesheet" type="text/css" href="{% static 'MontalcinoForecastsApp/css/main.css' %}">
    
    <!-- Scripts -->
    
    <!-- jQuery, Popper and Bootstrap -->
    <script src="{% static "lib/jquery/jquery.min.js" %}"></script>
    <script src="{% static "lib/popper/popper.min.js" %}"></script>
    <script src="{% static "lib/bootstrap/bootstrap.min.js" %}"></script>
    
    <!-- Air-datepicker -->
    <script src="{% static "MontalcinoForecastsApp/lib/air-datepicker/js/datepicker.min.js" %}"></script>
    <script src="{% static "MontalcinoForecastsApp/lib/air-datepicker/js/i18n/datepicker.en.js" %}"></script>

    <!-- Fusion charts -->
    <script src="{% static "lib/fusioncharts/fusioncharts.js" %}"></script>
    <script src="{% static "lib/fusioncharts/fusioncharts.charts.js" %}"></script>
    <script src="{% static "lib/fusioncharts/themes/theme.black-timeseries.js" %}"></script>
    <script src="{% static "lib/fusioncharts/themes/fusioncharts.theme.candy.js" %}"></script>
    <script src="{% static "lib/fusioncharts/jquery-fusioncharts.min.js" %}"></script>
    
    <script>
        var startDateString = "{{start_db}}";
        var endDateString = "{{end_db}}";
    </script>
    
    {% block js %}
    {% endblock %}

    <script src="{% static "MontalcinoForecastsApp/js/base.js" %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-transparent">
        <div class="container-fluid">
            
            <a class="navbar-brand" href="{% url 'MontalcinoForecastsApp:simplified' %}">
                <span>Montalcino Forecasts App</span>
            </a>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-kebab"></span>
                <span class="navbar-kebab"></span>
                <span class="navbar-kebab"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li id="simplified-link" class="nav-item px-2">
                        <h5><a class="nav-link" href="{% url 'MontalcinoForecastsApp:simplified' %}">App Semplificata</a></h5>
                    </li>
                    <li id="complete-link" class="nav-item px-2">
                        <h5><a class="nav-link" href="{% url 'MontalcinoForecastsApp:complete' %}">App Completa</a></h5>
                    </li>
                    <li id="home-link" class="nav-item px-2">
                        <h5><a class="nav-link" href="{% url 'MontalcinoForecastsApp:help' %}">Help</a></h5>
                    </li>
                </ul>
            </div>
            
        </div>
    </nav>

    <main>
        {% block main %}
        {% endblock %}
        
        <a href="#" id="top-btn">
            <span class="sr-only">Back to top arrow</span>
        </a>
    </main>
    
    <footer class="pt-3 pb-4 w-100">
        <div class="container">
            <div class="text-center" style="opacity: 0.7;">
                &copy;2020 made by Beatrice Paoli
            </div>
        </div>
    </footer>
</body>
</html>

MontalcinoForecastsApp/templates/MontalcinoForecastsApp/complete.html
{% extends "MontalcinoForecastsApp/base.html" %}

{% block js %}
{% load static %}
<script src="{% static "MontalcinoForecastsApp/js/complete.js" %}"></script>
<script>    
    $(document).ready(function() {
        $("#complete-link").addClass("active");
        $("#complete-link").find("a").append('<span class="sr-only">(current)</span>');
        
        {% if start_train_date %}
        vintageCountFromStrings("{{ start_train_date }}", "{{ end_train_date }}", "#vintages");
         
        postData = {
            csrfmiddlewaretoken: "{{ csrf_token }}",
            startTrainDate: "{{ start_train_date }}",
            endTrainDate: "{{ end_train_date }}",
            regrCombo: {{ regr_combo }}
        };
        {% endif %}
        
        {% if anchor %}
        window.location = '#{{ anchor }}';
        {% endif %}
    });
</script>
{% endblock %}

{% block main %}
<div class="container">
    
    <div class="row">
        <div class="card w-100">
            <div class="card-header"><h4 class="card-title">Addestramento del modello nuovo</h4></div>
            <div class="card-body">
                <p class="pb-1 text-justify">Seleziona i parametri da utilizzare nella regressione lineare.</p>
                <form id="training-form" action="{% url 'MontalcinoForecastsApp:complete' %}" method="post">
                    {% csrf_token %}
                    <h6>Scegli un range di date:</h6>
                    <div class="d-flex flex-row flex-wrap pb-3">
                        <div>
                            <label class="m-2" for="startDate">Inizio: </label>
                            <input class="date-input readonly" type="text" id="startDate" placeholder="gg/mm/aaaa" name="startDate" required>
                        </div>
                        <div>
                            <label class="m-2" for="endDate">Fine: </label>
                            <input class="date-input readonly" type="text" id="endDate" placeholder="gg/mm/aaaa" name="endDate" required>
                        </div>
                    </div>
                    <h6>Scegli gli indici bioclimatici:</h6>
                    <div class="d-flex flex-row flex-wrap pb-3">
                        {% for regr in form_regressors %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="regr-{{ regr.id }}" name="regr-{{ regr.id }}" value="regr-{{ regr.id }}">
                            <label class="form-check-label" for="regr-{{ regr.id }}">{{ regr.name }}</label>
                        </div>
                        {% endfor %} 
                    </div>
                    <button class="btn btn-purple" type="submit">Ok</button>
                </form>
            </div>
        </div>
    </div>

    <div class="row">
        {%if err_msg %}
        <div class="alert alert-danger" role="alert">Errore: {{ err_msg }}</div>
        {% endif %}
    </div>
    
    {% if table_data %}
    
    <a id="results-section"></a>
    <div class="row">
        <div class="col-lg-4 pl-0 under-lg-pr-0 d-flex align-items-stretch">
            <div class="card w-100">
                <div class="card-header">
                    <h4 class="card-title">Risultati</h4>
                    <h6>Regressione lineare</h6>
                </div>
                <div class="card-body">
                    <div class="py-1">
                        Periodo: <span class="numbers">{{ start_train_date }}</span> - <span class="numbers">{{ end_train_date }}</span>
                    </div>
                    <div class="py-1">N. annate: <span class="numbers" id="vintages"></span></div>
                    <div class="py-1">N. regressori: <span class="numbers">{{ regr_count }}</span></div>
                    <div class="py-1">R<sup>2</sup>: <span class="numbers">{{ r2|floatformat:2 }}</span></div>
                    <div class="py-1">R<sup>2</sup> aggiustato: <span class="numbers">{{ adj_r2|floatformat:2 }}</span></div>
                </div>
            </div>
        </div>
        <div class="col-lg-8 pr-0 under-lg-pl-0">
            <div class="card">
                <div class="card-header"><h4 class="card-title">Confronto tra qualità predetta e reale</h4></div>
                <div class="card-body">
                    <div id="chart">{{ chart_out|safe }}</div>
                </div>
            </div>
        </div>
    </div>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
        {%for regr, icon, coef, pval in table_data %}
        <div class="col mb-4">
            <div class="card h-100">
                <div class="card-header">
                    <div class="info-icon"><i class="{{ icon }}"></i></div>
                    <h6>{{ regr }}</h6>
                </div>
                <div class="card-body">
                    <p>Coefficiente: <span class="numbers">{{ coef|floatformat:4 }}</span></p>
                    <p>Valore p: <span class="numbers">{{ pval|floatformat:2 }}</span></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="row">
        <div class="card w-100">
            <div class="card-header pb-0"><h4 class="card-title">Previsioni</h4></div>
            <div class="card-body pt-0">
                <form id="forecast-form" action="" method="post">
                    <label for="forecastYear">Scegli l'anno su cui vuoi fare la previsione: </label>
                    <input class="date-input readonly" type="text" id="forecastYear" placeholder="aaaa" name="forecastYear" required>
                    <br>
                    <button class="btn btn-purple mb-4 mt-2" type="submit">Ok</button>
                </form>

                <div class="rating-container py-1 text-center d-flex flex-row flex-wrap justify-content-center">
                    <div class="px-3">
                        <svg id="star-1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 .587l3.668 7.568 8.332 1.151-6.064 5.828 1.48 8.279-7.416-3.967-7.417 3.967 1.481-8.279-6.064-5.828 8.332-1.151z"/></svg>
                    </div>
                    <div class="px-3">
                        <svg id="star-2" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 .587l3.668 7.568 8.332 1.151-6.064 5.828 1.48 8.279-7.416-3.967-7.417 3.967 1.481-8.279-6.064-5.828 8.332-1.151z"/></svg>
                    </div>
                    <div class="px-3">
                        <svg id="star-3" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 .587l3.668 7.568 8.332 1.151-6.064 5.828 1.48 8.279-7.416-3.967-7.417 3.967 1.481-8.279-6.064-5.828 8.332-1.151z"/></svg>
                    </div>
                    <div class="px-3">
                        <svg id="star-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 .587l3.668 7.568 8.332 1.151-6.064 5.828 1.48 8.279-7.416-3.967-7.417 3.967 1.481-8.279-6.064-5.828 8.332-1.151z"/></svg>
                    </div>
                    <div class="px-3">
                        <svg id="star-5" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 .587l3.668 7.568 8.332 1.151-6.064 5.828 1.48 8.279-7.416-3.967-7.417 3.967 1.481-8.279-6.064-5.828 8.332-1.151z"/></svg>
                    </div>
                </div>
                
                <div id="forecast-results"></div>
                
            </div>
        </div>
    </div>

    <div class="row">
        <div id="forecast-error"></div>
    </div>

    {% endif %}

</div>
{% endblock %}